version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    # Uncomment the following lines to run the migrations before running the server
    # entrypoint: ["/app/entrypoint.sh"]
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db

  db:
    image: postgres:16.0
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: scheduler_dev
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    ports:
      - "8080:8080"

volumes:
  pg_data:
